app:
  pgURL: DATABASE_URL
  pgURLWercker: WERCKER_POSTGRESQL_URL
  port: PORT
  tcApi: TC_API_URL
  tcUser: LC_USER_SERVICE
  kue:
    eventQueue: DISCUSSION_EVENT_QUEUE
    prefix: KUE_PREFIX
  redis:
    host: REDIS_HOST
    port: REDIS_PORT
auth0:
  client: TC_AUTH0_CLIENT
  secret: TC_AUTH0_SECRET
auth:
  enabled: TC_AUTH_ENABLED
