app:
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  port: 10010
  loadDoc: true
  tcApi: http://api.topcoder.com/v2
  tcUser: http://dev-lc1-user-service.herokuapp.com
  query:
    pageSize: 20
    onlyRootMessages: false
  dbOptions:
    paranoid: true
    timestamps: true
  kue:
    prefix: q
    eventQueue: 60_new_discussion_message
  redis:
    port: 6379
    host: 127.0.0.1
auth0:
  client: ''
  secret: ''
auth:
  enabled: false
  perms:
    - challengeApp
  paths:
    - httpVerb: DELETE
      path: '*'
    - httpVerb: PUT
      path: '*'
    - httpVerb: POST
      path: '*'
    - httpVerb: GET
      path: '/discussion/*'