app:
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  pg:
    database:
    username:
    password:
    host:
    dialect:
    port:
  port: 10010
  query:
    pageSize: 20
    onlyRootMessages: false