app:
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  port: 10010
  loadDoc: true
  tcApi: http://api.topcoder.com/v2
  disableAuth: false
  query:
    pageSize: 20
    onlyRootMessages: false
  dbOptions:
    paranoid: true
    timestamps: true
auth0:
  client: ''
  secret: ''
